name: push-notification
on:
  schedule:
    - cron: "*/2 11-23 * * *"
  workflow_dispatch:

jobs:
  update_symbol_list:
    name: run script periodically
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Download hash file
        uses: actions/download-artifact@v2
        with:
          name: hash_file
      - name: Run Script
        env:
          PUSH_BULLET: ${{ secrets.PUSH_BULLET }}
        run: |
          python main.py
      - name: Save hash file
        run: |
          echo "$(cat previous_hash.txt)" > previous_hash.txt
        artifact:
          paths:
            - previous_hash.txt
